name: Lint Commit Messages
on:
 push:
   branches:
     - "main"
 pull_request:
    branches:
      - "main"

jobs:
  commitlint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
