name: "node unit tests"

on: [pull_request, workflow_dispatch]
jobs:
  unit_tests:
    uses: https://github.com/ya-kimura/workflow-call/.github/workflows/ci.node_unit_test.yml@main
    secrets:
        token: ${{ secrets.GITHUB_TOKEN }}
