name: CI Workflow
on: [pull_request, workflow_dispatch]
jobs:
  unit_tests:
    uses: ya-kimura/workflow-call/.github/workflows/module.nodejs_unit_tests.yml@main
    with:
      runnerLabel: "ubuntu-20.04"

 

