name: CI Workflow
on: [pull_request, workflow_dispatch]
jobs:
  unit_tests:
    uses: ya-kimura/workflow-call/.github/workflows/ci.nodejs_unit_test.yml@main
    with:
      runnerLabel: "ubuntu-20.04"

  commitlint:
    uses: ya-kimura/workflow-call/.github/workflows/ci.lint.yml@master
    with:
      runnerLabel: "ubuntu-20.04"
 